# PV Sentinel MVP Configuration
# All improvements must NOT degrade existing validated functionality

system:
  logging_level: "DEBUG"
  audit_mode: true
  validation_mode: false
  app_name: "PV Sentinel"
  version: "1.0.0-MVP"
  environment: "local"

# Model Configuration
models:
  primary_model: "mistral-7b-instruct"
  model_path: "models/mistral-7b-instruct-v0.1.Q4_K_M.gguf"
  prompt_directory: "prompts/"
  model_hash_tracking: true
  version_control: true
  max_tokens: 2048
  temperature: 0.3
  top_p: 0.9
  context_length: 4096

# Speech-to-Text Configuration
stt:
  model: "whisper.cpp"
  model_path: "models/ggml-base.en.bin"
  language: "en"
  enable_readback: true
  confirmation_required: false

# RAG (Retrieval-Augmented Generation) Settings
rag:
  engine: "langchain"
  vector_store: "chromadb"
  document_path: "documents/"
  chunk_size: 1000
  chunk_overlap: 200
  similarity_threshold: 0.7
  max_documents: 5

# User Management and Roles
users:
  multi_user_support: true
  role_based_access: true
  audit_trail: true
  roles:
    - drafter
    - reviewer
    - auditor
    - admin
  session_timeout: 3600  # seconds

# Patient Safety Features (Critical P0 Requirements)
patient_safety:
  context_preservation: true
  voice_confirmation: true
  narrative_comparison: true
  patient_story_field: true
  context_validation: true

# Database Configuration
database:
  type: "sqlite"
  path: "storage/pv_sentinel.db"
  backup_enabled: true
  retention_days: 2555  # 7 years for GxP compliance

# Export Settings
export:
  formats: ["pdf", "json", "xml"]
  include_metadata: true
  include_audit_trail: true
  digital_signature: false  # Future enhancement

# Regulatory Compliance
regulatory:
  gvp_alignment: true
  faers_compliance: true
  medra_version: "26.0"
  e2b_r3_support: false  # Future enhancement
  psur_module: false     # Future enhancement

# Security and Privacy
security:
  local_only: true
  gdpr_compliant: true
  encryption_at_rest: true
  session_encryption: true
  data_anonymization: true
  consent_tracking: true
  mask_pii: true
  retain_patient_context: true

# PII Protection Configuration (Phase 1 Feature)
pii_protection:
  protection_enabled: true
  auto_detection: true
  role_based_masking: true
  access_logging: true
  anonymization_enabled: true
  detection_threshold: 0.7
  mask_in_logs: true
  mask_in_exports: false
  custom_patterns: []
  
  # Enhanced role-based masking rules
  role_masking:
    auditor:
      mask_names: false
      mask_addresses: true
      mask_phones: true
      mask_emails: true
      mask_dates: false
      mask_mrns: true
    readonly:
      mask_names: true
      mask_addresses: true
      mask_phones: true
      mask_emails: true
      mask_dates: true
      mask_mrns: true
    drafter:
      mask_names: false
      mask_addresses: true
      mask_phones: true
      mask_emails: false
      mask_dates: false
      mask_mrns: false
    reviewer:
      mask_names: false
      mask_addresses: false
      mask_phones: false
      mask_emails: false
      mask_dates: false
      mask_mrns: false

# Patient Voice Protection Configuration (Phase 2 Feature)
patient_voice:
  protection_enabled: true
  extraction_threshold: 0.7
  auto_lock_enabled: true
  log_modification_attempts: true
  
  # Voice extraction settings
  extraction:
    include_direct_quotes: true
    include_reported_speech: true
    include_emotional_expressions: true
    include_temporal_expressions: true
    minimum_fragment_length: 5
    maximum_fragments_per_case: 50
  
  # Protection levels
  protection_levels:
    read_only: "Cannot be modified by anyone"
    protected: "Can be annotated by humans but not modified by AI"
    locked: "Completely immutable with integrity verification"

# Narrative Comparison Configuration (Phase 2 Feature)
narrative_comparison:
  enabled: true
  auto_severity: true
  require_justification: true
  clinical_terms_file: "config/clinical_terms.json"
  
  # Comparison settings
  comparison:
    enable_line_diff: true
    enable_word_diff: true
    context_window: 3
    highlight_clinical_changes: true
    auto_categorize_changes: true
  
  # Review requirements
  review_requirements:
    critical_changes_require_review: true
    significant_changes_threshold: 3
    require_justification_for_severity: ["critical", "significant"]
    auto_flag_medication_changes: true
    auto_flag_temporal_changes: true
  
  # Version management
  versioning:
    max_versions_per_case: 50
    auto_create_backup: true
    enable_rollback: true
    lock_final_versions: true

# Validation and Quality Assurance
validation:
  gamp5_aligned: true
  prompt_locking: true
  change_control: true
  automated_testing: true
  validation_protocols: "validation/"

# Frontend Configuration
frontend:
  framework: "streamlit"
  theme: "light"
  auto_refresh: false
  max_file_size: 10  # MB

# Logging and Monitoring
logging:
  level: "INFO"
  file: "logs/pv_sentinel.log"
  max_size: 100  # MB
  backup_count: 5
  include_timestamps: true
  include_user_actions: true
  include_model_metadata: true

# Performance Settings
performance:
  max_concurrent_users: 10
  response_timeout: 30  # seconds
  cache_enabled: true
  cache_ttl: 3600  # seconds 