[global]
# dataFrameSerialization setting has been deprecated

[server]
runOnSave = true
port = 8501
enableCORS = false
enableXsrfProtection = false

[browser]
serverAddress = "localhost"
gatherUsageStats = false

[theme]
primaryColor = "#2e7bcf"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730" 